gdax:
  api
    baseUrl: "https://api.gdax.com"
    testUrl: "https://public.sandbox.gdax.com"
  passphrase: ""
  key: ""
  secret: ""
  enable: "true"
  strategy:
    movingAverage:
      initDelta: "15"

logging:
  file: logs/dev_app.log
  level:
    org.springframework.web: ERROR