import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'sunxi' at '1/22/18 8:26 PM' with Gradle 2.6
 *
 * @author sunxi, @date 1/22/18 8:26 PM
 */
public class LibraryTest {

}
